### ISSUE TITLE
📝 Documentation and Asset Setup

### ISSUE THREAD

**Issue by topksampler** [lalith1403/termipals#6]
Set up project documentation and initial ASCII art assets

Tasks:
- [ ] Create detailed ARCHITECTURE.md
- [ ] Write contributor guidelines
- [ ] Add initial ASCII art templates
  - Cow
  - Cat
  - Dog
- [ ] Document ASCII art format
- [ ] Add examples

Format for ASCII art files:
```yaml
name: [animal_name]
tags:
  - [tag1]
  - [tag2]
art: |
  [ASCII art here]
```

Notes:
- Use YAML for easy parsing
- Include clear examples
- Document contribution process
